# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Sharath Bennur
email:            sharath.bennur@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
tagline:          "Personal Website"
url:              "https://sharathbennur.github.io"
baseurl:          ""
author:
  name:           "Sharath Bennur"
  url:            "https://www.sharathbennur.com"

paginate:         5
paginate_path:    "/blog/page:num/"
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Sidebar link settings
sidebar_home_link:  false
sidebar_blog_link:  "/blog"   # By default, your home page is your blog
                              # page. If you change your paginate_path,
                              # set this to the root of the paginate_path
                              # to enable a separate blog link.

# Tracker
google_analytics:   G-M0P4CVCF8R

# Exclude pdfs from site-map
defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false